### ISSUE TITLE
make all contributors appear on the new line below the previous 

### ISSUE THREAD

**Issue by peterbsmith2** [peterbsmith2/pull-requests#7]
### Current Behavior
- all contributors in the README are displaying on the same line

### Desired Behavior
- lets show them all on different lines

**Comment by tmonks** [comment]
Why do they look like they are on separate lines to me?

**Comment by exratione** [comment]
The file is markdown - it needs some light formatting.

**Comment by peterbsmith2** [comment]
```md
Doug
Peter
```

we need to add two spaces to the end of every line so they appear correct
```md
Doug  <== there are two spaces here, please add two spaces to the end of every line in the README
Peter
```

**Comment by peterbsmith2** [comment]
Looks like #8  addresses this

**Comment by peterbsmith2** [comment]
Nailed It.
